import ModalComplete from '@/components/ModalComplete'
import ModalConfirm from '@/components/ModalConfirm'
import ModalDetail from '@/components/ModalDetail'
import ModalSearch from '@/components/ModalSearch'
import Providers from '@/components/Providers'
import ScrollToTop from '@/components/ScrollToTop'
import Footer from '@/layouts/Footer'
import Header from '@/layouts/Header'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='vi'>
      <Providers>
        <body className={`${geistSans.variable} ${geistMono.variable} bg-[#FFF6DE] antialiased`}>
          <Header />
          {children}
          <ModalDetail />
          <ModalConfirm />
          <ModalComplete />
          <ModalSearch />
          <ScrollToTop />
          <Footer />
        </body>
      </Providers>
    </html>
  )
}
